spring:
  application:
    name: wasm-playground
  profiles:
    active: go

extism:
  plugin:
    allowed-hosts: localhost
    execution-strategy: default

logging:
  level:
    io.viax.wasmplayground.service.DefaultExtismPluginService: debug

---

spring:
  config:
    activate:
      on-profile: js

extism:
  plugin:
    path: ./extism/simple-js/plugin.wasm

---

spring:
  config:
    activate:
      on-profile: rust

extism:
  plugin:
    path: ./extism/simple-rust/plugin.wasm

---

spring:
  config:
    activate:
      on-profile: go

extism:
  plugin:
    path: ./extism/simple-go/plugin.wasm
